version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: wanderlust-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: wanderlust
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - wanderlust-network

  redis:
    image: redis:7.2-alpine
    container_name: wanderlust-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wanderlust-network

  backend:
    image: devopswithjunaid/wanderlust-backend:latest
    container_name: wanderlust-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/wanderlust?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    networks:
      - wanderlust-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: devopswithjunaid/wanderlust-frontend:latest
    container_name: wanderlust-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      VITE_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - wanderlust-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  wanderlust-network:
    driver: bridge
